version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    tty: true
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"